# Need this cuda image
FROM hardikparwana/cuda116desktop:ipopt
RUN apt-get update
RUN apt install -y python3-pip
RUN pip3 install numpy==1.22.3 matplotlib sympy argparse scipy==1.8.0
RUN apt-get update
RUN apt-get -y install vim
RUN apt -y install ffmpeg
RUN apt-get install pkg-config

RUN apt update
RUN apt install -y wget build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt install -y python3.11
RUN apt-get install -y python3.11-distutils
RUN apt-get install -y python3.11-dev
RUN apt install -y curl
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11

COPY ./MPCC/C++/install.sh /home/install.sh
WORKDIR /home
RUN apt install -y cmake
RUN ./install.sh

RUN python3.11 -m pip install matplotlib>=3.5.1
RUN python3.11 -m pip install munch>=2.5.0
RUN python3.11 -m pip install PyYAML>=6.0
RUN python3.11 -m pip install imageio>=2.14.1
RUN python3.11 -m pip install dict-deep>=4.1.2
RUN python3.11 -m pip install scikit-optimize>=0.9.0
RUN python3.11 -m pip install scikit-learn>=1.3.0
RUN python3.11 -m pip install gymnasium>=0.28
#RUN python3.11 -m pip install torch>=1.10.2
RUN python3.11 -m pip install "torch<2.0.0,>=1.10.2"
RUN python3.11 -m pip install gpytorch>=1.6.0
RUN python3.11 -m pip install tensorboard>=2.12.0
RUN python3.11 -m pip install casadi>=3.6.0
RUN python3.11 -m pip install pybullet>=3.2.0
RUN python3.11 -m pip install numpy>=1.22.1
RUN python3.11 -m pip install cvxpy>=1.1.18
RUN apt-get install -y libgmp-dev
RUN python3.11 -m pip install pytope>=0.0.4
RUN python3.11 -m pip install Mosek>=10.0.18
RUN python3.11 -m pip install termcolor>=1.1.0
RUN python3.11 -m pip install pytest>=7.2.2
RUN python3.11 -m pip install pre-commit>=3.3.2
RUN python3.11 -m pip install PyQt5
RUN python3.11 -m pip install gym>=0.21.0
RUN apt install -y libxcb-cursor0
RUN apt-get install -y '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
RUN python3.11 -m pip install jaxlib jax
RUN python3.11 -m pip install notebook
RUN python3.11 -m pip install mpld3
RUN python3.11 -m pip install diffrax
